### ISSUE TITLE
Finish Player

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#85]
Currently the player does not support
- [x] Adaptive bitrate streaming  (auto lower quality when connection gets slow) (#98)
- [x] Errors, errors are handled poorly (we shouldnt just stop we should try recover)
- [x] Codec support (check if the browser supports the codecs before loading them) (#98)
- [ ] Unsupported browsers (check if the browser is unsupported and raise some flag or something)
- [x] Unit tests (partially #98)
